export enum KycStatus {
  NOT_STARTED = 'NOT_STARTED',
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
