export enum KycStatus {
  NOT_STARTED = 'NOT_STARTED',
  CREATED = 'CREATED',
  LINK_SENT = 'LINK_SENT',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  EXPIRED = 'EXPIRED',   
}
